version: '3.8'

services:
  laravel:
    restart: unless-stopped
    container_name: laravelapp
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./storage:/var/www/html/storage
    environment:
      BRASIL_API_URL: ${BRASIL_API_URL}
    ports:
      - "8080:80"
    networks:
      - n-laravel

networks:
  n-laravel:
    driver: bridge